// <auto-generated />
namespace SchoolSchedule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AuditoryNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuditoryNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201902221347528_AuditoryNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
